'use strict'

const RANGES_LAST_24_HOURS = 'LAST_24_HOURS'
const RANGES_LAST_7_DAYS = 'LAST_7_DAYS'
const RANGES_LAST_30_DAYS = 'LAST_30_DAYS'
const RANGES_LAST_6_MONTHS = 'LAST_6_MONTHS'
const RANGES_LAST_1_YEAR = 'LAST_1_YEAR'

module.exports = {
	RANGES_LAST_24_HOURS,
	RANGES_LAST_7_DAYS,
	RANGES_LAST_30_DAYS,
	RANGES_LAST_6_MONTHS,
	RANGES_LAST_1_YEAR,
}